WebSiram/Models/Activity.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebSiram.Models
{
    [Table("activites")]
    public class Activity
    {
        public int id { get; set; }
        public string? reg_no { get; set; }
        public string? status { get; set; }
        public string? description { get; set; }
        public DateTime created_at { get; set; }
        public string? created_by { get; set; }
        public DateTime? updated_at { get; set; }
        public DateTime? last_updated_at { get; set; }
        public string? updated_by { get; set; }
    }
}

WebSiram/Controllers/ActivitiesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using WebSiram.Models;
using WebSiram.ViewModels;

namespace WebSiram.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly ILogger<ActivitiesController> _logger;
        private IConfiguration _config;
        public ActivitiesController(ILogger<ActivitiesController> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        }

        public async Task<ActionResult> Index()
        {
            if (HttpContext.Session.GetString("user_id") == null)
            {
                //return RedirectToAction("Logout", "Auth");
            }
            string? accessToken = HttpContext.Session.GetString("token");

            List<Activity>? activity = new List<Activity>();

            string ApiUrl = _config["AppSettings:ApiUrl"];

            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            using (var client = new HttpClient(clientHandler))
            {
                client.BaseAddress = new Uri(ApiUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + accessToken);
                HttpResponseMessage Res = await client.GetAsync("api/Activity/GetActive");
                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    activity = JsonConvert.DeserializeObject<List<Activity>>(Response);
                }
                else
                {
                    return RedirectToAction("Index", "Auth");
                }
                return View(activity);
            }
        }

        // GET: UsersController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (HttpContext.Session.GetString("user_id") == null)
            {
                //return RedirectToAction("Logout", "Auth");
            }
            string? accessToken = HttpContext.Session.GetString("token");

            ActivityVM? activity = new ActivityVM();

            string ApiUrl = _config["AppSettings:ApiUrl"];

            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
            using (var client = new HttpClient(clientHandler))
            {
                client.BaseAddress = new Uri(ApiUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("Authorization", "Bearer " + accessToken);
                HttpResponseMessage Res = await client.GetAsync("api/Activity/Details/" +id);
                if (Res.IsSuccessStatusCode)
                {
                    var Response = Res.Content.ReadAsStringAsync().Result;
                    activity = JsonConvert.DeserializeObject<ActivityVM>(Response);
                }
                else
                {
                    return RedirectToAction("Index", "Auth");
                }
                return View(activity);
            }
        }










    }
}

WebSiram/Views/Activities/Details.cshtml
@model WebSiram.ViewModels.ActivityVM

@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Managemen Aplikasi</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Pangkat</a></li>
                        <li class="breadcrumb-item active">Index</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                    @await Html.PartialAsync("_MenuSettings")
                </div>
                <!-- /.col -->

                <div class="col-md-10">
                    <div class="card">
                        <div class="card-header p-2">
                            <h3 class="card-title">Transaksi</h3>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" aria-describedby="example1_info">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Reg No</th>
                                        <th>Tanggal</th>
                                        <th>Status</th>
                                        <th>Keterangan</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.details_activity)
                                    {
                                        <tr class="odd">
                                            <td class="dtr-control sorting_1" tabindex="0">@item.id</td>
                                            <td> <a asp-controller="Activities" asp-action="Details" asp-route-id="@item.reg_no">@item.reg_no</a></td>
                                            <td>@item.created_at.ToString("dd MMM yyyy HH:mm:ss")</td>
                                            <td>@item.status</td>
                                            <td>@item.description</td>
                                        </tr>
                                    }
                                </tbody>

                            </table>

                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

WebSiram/Views/Activities/Index.cshtml
@model IEnumerable<WebSiram.Models.Activity>

@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Managemen Aplikasi</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Pangkat</a></li>
                        <li class="breadcrumb-item active">Index</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                    @await Html.PartialAsync("_MenuSettings")
                </div>
                <!-- /.col -->

                <div class="col-md-10">
                    <div class="card">
                        <div class="card-header p-2">
                            <h3 class="card-title">Transaksi</h3>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" aria-describedby="example1_info">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Reg No</th>
                                        <th>Status</th>
                                        <th>Keterangan</th>
                                        <th>Tanggal</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="odd">
                                            <td class="dtr-control sorting_1" tabindex="0">@item.id</td>
                                            <td> <a asp-controller="Activities" asp-action="Details" asp-route-id="@item.reg_no">@item.reg_no</a></td>
                                            <td>@item.status</td>
                                            <td>@item.description</td>
                                            <td>@item.created_at.ToString("dd MMM yyyy")</td>
                                            <td class="text-center">
                                                <a asp-controller="Pangkat" asp-action="Edit" asp-route-id="@item.id"><i class="far fa-edit text-warning mr-2"></i></a>
                                           
                                            </td>
                                        </tr>
                                    }
                                </tbody>

                            </table>

                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->